"""文档表增加封面字段

Revision ID: 1786976f82e2
Revises: 38ea05478e42
Create Date: 2025-09-10 17:06:09.282406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1786976f82e2'
down_revision = '38ea05478e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_img', sa.String(length=256), nullable=True, comment='oss路径'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('cover_img')

    # ### end Alembic commands ###
