"""修改了文档标签表的bug,新增图片和文档图片关联表

Revision ID: 2c8c8d9f0def
Revises: 82bb6e5aef59
Create Date: 2025-08-08 15:32:35.907879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8c8d9f0def'
down_revision = '82bb6e5aef59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oss_key', sa.String(length=256), nullable=False, comment='oss的key值'),
    sa.Column('uploaded', sa.Boolean(), nullable=True, comment='是否成功上传oss'),
    sa.Column('in_use', sa.Boolean(), nullable=True, comment='使用到'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_image')
    op.drop_table('images')
    # ### end Alembic commands ###
