"""documents表新增标题字段

Revision ID: 38ea05478e42
Revises: 2c8c8d9f0def
Create Date: 2025-08-14 09:53:43.369973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38ea05478e42'
down_revision = '2c8c8d9f0def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True, comment='文章标题'))

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('in_use',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否使用到',
               existing_comment='使用到',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('in_use',
               existing_type=mysql.TINYINT(display_width=1),
               comment='使用到',
               existing_comment='是否使用到',
               existing_nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
