"""创建项目数据库

Revision ID: 75274726e21c
Revises: 
Create Date: 2025-05-06 23:46:44.972216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75274726e21c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False, comment='oss路径'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='md5名称'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appname', sa.String(length=128), nullable=False, comment='应用名称'),
    sa.Column('version', sa.String(length=64), nullable=False, comment='版本号'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='文件名'),
    sa.Column('size', sa.BigInteger(), nullable=False, comment='文件大小(字节)'),
    sa.Column('system', sa.String(length=64), nullable=False, comment='适用系统'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态(0-正常)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('ar', sa.String(length=256), nullable=True, comment='架构信息'),
    sa.Column('package_name', sa.String(length=256), nullable=False, comment='包名'),
    sa.Column('oss_key', sa.String(length=256), nullable=False, comment='oss的key值'),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_appname'), ['appname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_appname'))

    op.drop_table('packages')
    op.drop_table('icons')
    # ### end Alembic commands ###
