"""Initial migration

Revision ID: 7df4371e8806
Revises: 
Create Date: 2025-12-03 13:13:35.073759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df4371e8806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitter_id', sa.String(length=50), nullable=True),
    sa.Column('submitter_name', sa.String(length=50), nullable=True),
    sa.Column('handler_id', sa.String(length=50), nullable=True),
    sa.Column('handler_name', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('gitee_url', sa.String(length=255), nullable=True),
    sa.Column('ignore_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_change_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('operator_id', sa.String(length=50), nullable=True),
    sa.Column('operator_name', sa.String(length=50), nullable=True),
    sa.Column('operated_at', sa.DateTime(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_change_records')
    op.drop_table('issues')
    # ### end Alembic commands ###
