"""文档增加了一个short_content属性

Revision ID: 82bb6e5aef59
Revises: cd9bf545cb66
Create Date: 2025-08-08 10:43:25.154341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bb6e5aef59'
down_revision = 'cd9bf545cb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_content', sa.String(length=256), nullable=True, comment='短内容'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('short_content')

    # ### end Alembic commands ###
