"""add user table

Revision ID: 8cba950266f1
Revises: 75274726e21c
Create Date: 2025-05-15 14:27:14.458682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cba950266f1'
down_revision = '75274726e21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=50), nullable=False, comment='密码'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
