"""change status to is_debug

Revision ID: dbc7d260792f
Revises: 03998b5d26ec
Create Date: 2025-05-22 15:39:44.634912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbc7d260792f'
down_revision = '03998b5d26ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_debug', sa.Boolean(), nullable=False, comment='是否为调试包'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.SMALLINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='状态(0-正常)'))
        batch_op.drop_column('is_debug')

    # ### end Alembic commands ###
